[global]
toggles	=	[
	["true", "false"],
	["begin",	"end"],
	["monday", "tuesday",	"wednesday", "thursday", "friday", "saturday", "sunday"],
	["black",	"white"],
	["high", "low"],
	["horizontal", "vertical"],
	["inner",	"outer"],
	["left", "right"],
	["top",	"bottom"],
	["0",	"1", "-1"],
	["if", "else"],
	["on", "off"],
	["yes",	"no"],
	["==", "!="],
	["&&", "||"],
	["sin",	"cos"],
	["+",	"-"],
	["x",	"y"],
	["<",	">"],
	["disable",	"enable"],
	["private",	"public"],
]

[javascript]
toggles	=	[
	["window", "document"],
	["const",	"let", "var"],
	["import", "export"],
	["join", "split"],
	["JSON.parse", "JSON.stringify"],
	["parse",	"stringify"],
	["pop",	"push"],
	["unshift",	"shift"],
	["test.only",	"test"],

	["onAnimationStart", "onAnimationEnd"],
	["onChange", "onInput",	"onSubmit"],
	["onClick",	"onDoubleClick"],
	["onCompositionStart", "onCompositionEnd"],
	["onCopy", "onCut",	"onPaste"],
	["onDragEnter",	"onDragLeave"],
	["onDragStart",	"onDragEnd"],
	["onFocus",	"onBlur"],
	["onKeyDown",	"onKeyUp"],
	["onMouseDown",	"onMouseUp"],
	["onMouseEnter", "onMouseLeave"],
	["onTouchStart", "onTouchEnd"],
	["addEventListener", "removeEventListener"],
	["animationstart", "animationend"],
	["change", "input",	"submit"],
	["dblclick", "click"],
	["compositionstart", "compositionend"],
	["copy", "cut",	"paste"],
	["dragenter",	"dragleave"],
	["dragstart",	"dragend"],
	["focus",	"blur"],
	["keydown",	"keyup"],
	["mousedown",	"mouseup"],
	["mouseenter", "mouseleave"],
	["touchstart", "touchend"],

	["===",	"!=="],
	["setInterval",	"setTimeout"],
	["clearInterval",	"clearTimeout"],
	["in", "of"],
]

[rust]
toggles	=	[
	["filter", "map_filter"],
	["find", "map_find"],
	["Option", "Result"],
]

[vue]
extends	=	["html"]
toggles	=	[
	["v-if", "v-show"],
]

[elm]
toggles	=	[
	["true", "false"],
]

[html]
extends	=	["javascript"]
toggles	=	[
	["span", "div"],
  ["head", "body"],
  ["header", "footer"],
  ["ol", "ul"],
  ["tr", "td"],
]

[elixir]
toggles	=	[
	["and",	"or"],
	["Enum", "Stream"],
]

[zig]
toggles	=	[
	["const",	"var"],
]

[typescript]
extends	=	["javascript"]
toggles	=	[
	["type", "interface"],
	["nullable", "optional"],
]
